### ISSUE TITLE
Minor set issues

### ISSUE THREAD

**Issue by wlk0** [GeckoTH/arkham-horror#19]
Hi Tom,

A couple of issues I noticed in the core set:
1. The 'Predator or Prey' (agenda) has no alternate/back side
2. 'The Gathering' text (both front and back) is referencing the wrong symbol. Should be a tablet (γ) instead of an Elder One (δ).

Keep up the good work !

**Comment by GeckoTH** [comment]
Thanks for looking through this! I've fixed The Gathering card so it should be referencing the proper symbol now.

For the Predator or Prey card, the reason it doesn't have a backside is because the backside of that card is actually an Enemy. This means that the front side of the card is a horizontal card, and the backside is a vertical card. And OCTGN currently doesn't have a way to handle alternates that are different "sizes", so I had to make a small hack whereby flipping "Predator or Prey" over in-game actually replaces that card with the Enemy backside card.

Nice spot though!
