### ISSUE TITLE
F11 Shortcut conflicts with OCTGN's Fullscreen Ready Shortcut

### ISSUE THREAD

**Issue by hone** [GeckoTH/arkham-horror#28]
@rushl pointed out that the key we use for Exhaust conflicts with the fullscreen shortcut built in by OCTGN. We should find a new shortcut key for those two actions.

**Comment by rushl** [comment]
I'd suggest either shift-F11 and shift-F12, or F12 and shift-F12.

**Comment by wlk0** [comment]
Shift+something is not very user friendly for frequent operations.
Would rather have something that can be done with one hand.

**Comment by rushl** [comment]
I can see your point. On most keyboards, the shift key and the F12 key are very close. Do you have a small-factor keyboard with a shift key only on one side? Most keyboards have one shift key on each side.

**Comment by wlk0** [comment]
Right shift is close to F12 indeed, but as I'm right handed I usually use my left hand for keyboard shortcuts while pointing the mouse with the right hand, and left shift is more convenient because I'm also using many ctrl+<keys>, like ctrl+S, ctrl+E.
LotR on OCTGN use F7 for exhausting cards, and it's nice. Wish we had that key available for this :)
I'll probably end modding it for my own habits and remap the "remove tokens" to something else.

**Comment by rushl** [comment]
Actually, I had that change in the pipeline, but haven't had a chance to send it yet. :) I'll send that up. And F6/F7 would be fine with me for refresh states, if everyone else supports that.

**Comment by hone** [comment]
I'm :+1: on Shift + F1-5 for removing tokens, so we can clear up F keys for other stuff.

**Comment by wlk0** [comment]
Go for it !

**Comment by hone** [comment]
This was fixed in #42
